### ISSUE TITLE
launchdarkly_team_member: Missing role type "no_access"

### ISSUE THREAD

**Issue by LavaToaster** [launchdarkly/terraform-provider-launchdarkly#109]
Pretty much as the above says - the docs and code only list `reader` `writer` and `admin` as possible roles for a team member. `no_access` is also a valid value, and something I'd prefer using but cannot.

Api Ref: https://apidocs.launchdarkly.com/tag/Account-members#operation/postMembers

**Comment by lucywyman** [comment]
Fixed in 2.9.0! Let us know if you have any issues with it, and thanks for raising this!

**Comment by LavaToaster** [comment]
Hey @lucywyman 

Thanks for the prompt response on this! Apologies for not trying it out sooner, but it appears as if 2.9.0 didn't release. It's not tagged and I can't download it from the terraform registry.

**Comment by lucywyman** [comment]
Hm, ok, I think I know why but I need a +1 on a PR to merge so...hopefully someone can take a look tomorrow and we can get it successfully released! Sorry for the hassle.

**Comment by LavaToaster** [comment]
Hey @lucywyman, do you reckon this will be resolved today or should I raise a new issue so that it's kept track of outside of this closed one?

**Comment by lucywyman** [comment]
I'm hoping it gets resolved today but I'll reopen this.

**Comment by lucywyman** [comment]
🙌🏼  https://registry.terraform.io/providers/launchdarkly/launchdarkly/2.9.0
