### ISSUE TITLE
Feature request - allow managing integrations via Terraform

### ISSUE THREAD

**Issue by arhill05** [launchdarkly/terraform-provider-launchdarkly#121]
Hello! Our team is working on managing our LaunchDarkly projects via Terraform, and it would be great if we could also manage the integrations. We're currently having to manually create an integration for one of our tools for each project, and having this manageable via Terraform would be much more ideal.

I'm happy to provide whatever information is useful for pushing this forward.

Thanks!

**Comment by ldhenry** [comment]
Hey @arhill05, you can manage a few of our integrations with the[ launchdarkly_audit_log_subscription](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/audit_log_subscription) today, but this does not cover our entire suite of integrations. which integration(s) were you looking to manage with Terraform?

**Comment by arhill05** [comment]
Thanks for the quick response @ldhenry! We are looking to manage the New Relic integrations.
