### ISSUE TITLE
Update documentation for launchdarkly_feature_flag

### ISSUE THREAD

**Issue by rcmatillion** [launchdarkly/terraform-provider-launchdarkly#128]
Hi!

I've had to look this up on a couple of separate occasions now, but I believe the [Terraform documentation](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/feature_flag) for the `launchdarkly_feature_flag` resource is missing an entry for the `archive` attribute.

A question about the attribute was initially raised [here](https://github.com/launchdarkly/terraform-provider-launchdarkly/issues/63) which points to [this release](https://github.com/launchdarkly/terraform-provider-launchdarkly/releases/tag/v2.1.0) for confirmation that it's available.

It would be great to get confirmation that this is, in fact, in place and whether the attribute is written as`archive` or if it's `archived` as some older issues suggest.

Thanks,
Rob

**Comment by lucywyman** [comment]
So it is! I'll update our documentation, thanks so much for raising this!

**Comment by lucywyman** [comment]
Just as a heads up, due to our release process this update may not get released until next week. But we'll get it out as soon as we can!
