### ISSUE TITLE
The `launchdarkly_project` resource key length requirement does not match existing resources.

### ISSUE THREAD

**Issue by scuba10steve** [launchdarkly/terraform-provider-launchdarkly#175]
When importing an existing project into a new Terraform repo, and then subsequently running a plan the provider responds back wtih an error `Error: expected length of key to be in the range (1 - 20), got <redacted>`.  I've ommitted the actual key, but the length is 26 characters as it exists in the SaaS.

For reference the code here: https://github.com/launchdarkly/terraform-provider-launchdarkly/blob/main/launchdarkly/resource_launchdarkly_project.go#L73 is seeming to be inconsistent with existing projects, is this something that could be adjusted?

Also, just to double check, I created a project within the SaaS and was able to create one with a key length longer than 20 characters:

![image](https://github.com/launchdarkly/terraform-provider-launchdarkly/assets/7774418/6132f251-a46b-4adc-8e87-2a86fe4f31d4)

**Comment by ldhenry** [comment]
He @scuba10steve, thanks for bringing this to our attention. We'll work on getting that updated in the next release. I'll let you know when it's available.

Thanks,
Henry

**Comment by scuba10steve** [comment]
@ldhenry I'd be happy to provide a PR, but I don't know what length requirement makes sense, or if it should just be removed entirely.  

Also, appreciate the feedback!

**Comment by scuba10steve** [comment]
@ldhenry Thanks for the quick turn around!  That should be sufficient for my use case.
