### ISSUE TITLE
Update provider to support BigSegment fields

### ISSUE THREAD

**Issue by christogav** [launchdarkly/terraform-provider-launchdarkly#188]
Currently the provider does not support additional fields required for BigSegments to be supported. Proposing to add them so that we can use the provider for management of BigSegments.

https://github.com/launchdarkly/terraform-provider-launchdarkly/pull/187

**Comment by ldhenry** [comment]
This is a good idea. Our team will review your submission on Monday with the goal of getting it released next week.

**Comment by ldhenry** [comment]
Hey @christogav,

Thanks for your contribution in https://github.com/launchdarkly/terraform-provider-launchdarkly/pull/187! We just released [v2.16.0](https://github.com/launchdarkly/terraform-provider-launchdarkly/releases/tag/v2.16.0) of the Terraform provider that includes your change.

On thing to keep in mind is that you will be unable to manage the individual big segment targets in Terraform using the `launchdarkly_segment` resource. However you will be able to create the Big Segment using Terraform and then upload the targets via CSV using our UI or public APIs.

Thanks,
Henry
