### ISSUE TITLE
Allow for configuring approval system for environments

### ISSUE THREAD

**Issue by fcma-ahill1** [launchdarkly/terraform-provider-launchdarkly#190]
Hello!

Our team manages LaunchDarkly projects and environments via Terraform. We've recently configured the ServiceNow integration to handle the creation of change requests, but it appears I cannot configure that via the Terraform provider.

I'd like to add a feature request for this :)

**Comment by ldhenry** [comment]
Hey @fcma-ahill1 and @arhill05, we released this in [v2.17.0](https://github.com/launchdarkly/terraform-provider-launchdarkly/releases/tag/v2.17.0). Thanks for your PR, @arhill05
