### ISSUE TITLE
Can't set a team as maintainer in terraform

### ISSUE THREAD

**Issue by lughino** [launchdarkly/terraform-provider-launchdarkly#194]
Hi there,

I'm porting an existing project to Terraform. We have assigned the feature flags maintainers to specific teams, but when I import that feature flag in terraform, I see in the state that the `maintainer_id` is `null`.
I also don't have the ability to retrieve the `id` from the `launchdarkly_team` data source, making it impossible to associate the team as the maintainer of the flag.

It is worth noting that assigning teams as maintainers is possible in the UI.
How can I achieve this?

Thanks

**Comment by ldhenry** [comment]
Hello @lughino,

Thanks for brining this to our attention. It seems this is an oversight on part and something we would like to add in the near future. I've created a ticket to track this work and we'll be sure to update this issue when it is available.

Thanks,
Henry

**Comment by sloloris** [comment]
Hi @lughino! 

I'm happy to report that we've fixed this to reflect [our API](https://apidocs.launchdarkly.com/tag/Feature-flags#operation/patchFeatureFlag): you should now be able to set a team as a maintainer on a feature flag using the new `team_maintainer_key` field, which should correspond to a team resource or data source's `key` _or_ `id` field (both are set to the same value in the provider). 

We're working on a few extra fixes this week and hope to release for tomorrow (Friday) or early next week; I will follow up when we do.

Please feel free to reach out if you have any other issues! Thank you for contributing to improving our provider :)

**Comment by sloloris** [comment]
Hi @lughino ! Just a quick update to say that this has been released in v2.18.0. Please do let us know if you have any other issues and have a great weekend!

**Comment by lughino** [comment]
Thank you @sloloris for this nice addition. Have a great weekend too
