### ISSUE TITLE
Release tag appears to have been made before the release was merged

### ISSUE THREAD

**Issue by shuttlescott** [launchdarkly/terraform-provider-launchdarkly#204]
Hi,

My team and I just bumped our Terraform Provider version hoping to fix the "Default off variation must be a valid index in the variations list" as described to be fixed in the latest release https://github.com/launchdarkly/terraform-provider-launchdarkly/releases/tag/v2.18.1

Upon closer inspection, after the bump did not solve the issue, it appears that the release was tagged right before the release branch was merged back to main.

https://github.com/launchdarkly/terraform-provider-launchdarkly/commits/

Has this been caught already? Seems like it should be a simple fix to recreate that tag.

**Comment by sloloris** [comment]
Hi @shuttlescott,

So so sorry for this oversight. We've just released some minor things in v2.18.2 which should also include the bug fix you are looking for.

Thank you for bringing this to our attention!
