### ISSUE TITLE
add critical property to `launchdarkly_environment` resource

### ISSUE THREAD

**Issue by cdschneider** [launchdarkly/terraform-provider-launchdarkly#206]
# Overview

[Environments can be marked as `critical`](https://docs.launchdarkly.com/home/organize/environments#critical-environments), so the `launchdarkly_environment` resource should support this by adding a boolean property named `critical`.

**Comment by cdschneider** [comment]
Hi @lucywyman, any update on this?

**Comment by lucywyman** [comment]
Yes! The person who implemented it wants to add some more tests before releasing, we have a ticket for that that I believe is getting worked on this week. I'm sorry for the delay, we're busy right now preparing for our Galaxy conference - I appreciate your patience!

**Comment by sunnyguduru** [comment]
Hello, we've released v2.18.3 with the `critical` property on `launchdarkly_environment`.
