### ISSUE TITLE
Please add examples of each of the operator types to the feature_flag_environment resource type doc

### ISSUE THREAD

**Issue by EmilHorne** [launchdarkly/terraform-provider-launchdarkly#207]
https://docs.launchdarkly.com/sdk/concepts/flag-evaluation-rules#operators

https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/feature_flag_environment

**Comment by lucywyman** [comment]
Hi @EmilHorne ! You can see we have a lot of operator types, my feeling is this would make our documentation very verbose with relatively little benefit. Is there a particular operator you were confused by?

**Comment by EmilHorne** [comment]
There's no direct link from the Terraform documentation (or from the regular API documentation) to the operator list that I referenced.

The example in the Terraform documentation is a template for copy/pasting snippets into real Terraform files.  Having to look up operators and then guess at the syntax for the rest of the structure is a lot of extra effort, trial and error.

Providing specific examples will make it easier for teams to scale their use of the Terraform provider.  Not having them in the documentation at all leaves a lot of uncertainty for each end user to overcome.

If verbosity is a concern, specific examples can be split into multiple sections.  I view this as unnecessary complication.  A long example isn't a problem as long as the structure is easy to follow.  That is the purpose of an example.

**Comment by ldhenry** [comment]
Hey @EmilHorne, thanks for the feedback. We've updated the [launchdarkly_feature_flag_environment](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/feature_flag_environment) and [launchdarkly_segment](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/segment) examples based on your feedback.
