### ISSUE TITLE
[LaunchDarkly Segment] What is the difference between `rules.clauses.context_kind` and `rule.rollout_context_kind`?

### ISSUE THREAD

**Issue by ozheng-circle** [launchdarkly/terraform-provider-launchdarkly#211]
I am confused specifically about `rule.rollout_context_kind`. 

It makes sense that `rules.clauses.context_kind` targets specific context kind attributes. However, how does `rule.rollout_context_kind` work alongside a flag? 

1. `rule.rollout_context_kind` , so if my segment rule matches say, `person` context but rollout context is set to `user` (also by default), does this mean the segment would evaluate false if my flag is evaluating a `person` context? 
2. What is the point if I specify these two attributes differently? In other words, if my rule is meant for a `person` context but rollout context is for `user`, it wouldn't mean anything. 
3. In doc, `bucket_by` says `The attribute by which to group users together,`  so is this only applied if `rule.rollout_context_kind=user`? What if my rollout context kind is different? Additionally, it does not seem like to me in the UI there's an option to specify rollout by attributes? 

It makes more sense to me that both of these context kinds are always the same

**Comment by ozheng-circle** [comment]
Oh also just discovered that the [documentation](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/segment#nested-schema-for-rulesclauses) is incorrect:

> context_kind (String) The context kind associated with this rule clause. This argument is only valid if `rollout_weights` is also specified. If omitted, defaults to user.

but `rollout_weights` is not an attribute, did you mean `weight`?

**Comment by sloloris** [comment]
Hi @ozheng-circle!

Whether or not both of these properties (`rules.clauses.context_kind` and `rule.rollout_context_kind`) apply for you depends on how you are targeting. For segments, these specifically apply for [rule-based segments](https://docs.launchdarkly.com/home/flags/rule-based-segments). In response to your question (1), this would depend on whether you were evaluating on a `person` context _only_ or whether you were evaluating on a [multi-context](https://docs.launchdarkly.com/home/observability/multi-contexts) containing both context types.

You may have rules that target on different types on contexts; for instance, you may have a flag that you want to turn on for specific users (perhaps the people who are working on it / testing it), thus targeting your rule on a `user` context kind, but then be rolling out your release based on `organization` contexts to ensure that different users within the same customer company do not receive different variations.

Similarly, if you have a rule-based segment, you may want your segment to include trial `account` contexts that are _also_ in a particular AWS region (possibly another context, depending on how you have your contexts set up), and then roll out to a subset of users within that. Something like this:
![Screenshot 2024-05-31 at 12 40 22](https://github.com/launchdarkly/terraform-provider-launchdarkly/assets/17100130/58c89ab3-24aa-45d4-a183-f069985b2d24)

For which the created `rules` response would look like this:
```
{
    "rules": [
        {
            "_id": "dba8f7f2-853c-4545-b1ca-71d3ea53ffbe",
            "clauses": [
                {
                    "_id": "2d95d8e0-5ec0-4e11-bb61-c6682384e23a",
                    "attribute": "isTrial",
                    "op": "in",
                    "values": [
                        true
                    ],
                    "contextKind": "account",
                    "negate": false
                },
                {
                    "_id": "10aee091-99a6-4f7b-98be-4cb432d7810f",
                    "attribute": "key",
                    "op": "in",
                    "values": [
                        "us-east-1"
                    ],
                    "contextKind": "aws-region",
                    "negate": false
                }
            ],
            "weight": 20000,
            "rolloutContextKind": "user",
            "description": "demo rule"
        }
    ], // etc rest of API response
}
```

So it's very possible that in your case (2) applies - depending on how you have your contexts set up, this may be a moot feature. Multi-contexts were only released last year so I'd imagine not all organizations are taking advantage of them yet.

I hope this helps!

Additionally, it does seem like you have discovered some errors in our docs - `rollout_weights` is a flag attribute, not a segment attribute. I believe we do mean to say `weights`. Additionally, the wording you draw attention to in (3) should say 'contexts' in lieu of 'users'. Thank you for drawing our attention to these! We will make sure to correct that for the next release.

**Comment by ozheng-circle** [comment]
@sloloris Thank you for the thorough and timely response! You have solved my questions sufficiently. Marking this as closed.

**Comment by ozheng-circle** [comment]
Actually @sloloris I do have another question. For [percentage rollout](https://docs.launchdarkly.com/sdk/concepts/flag-evaluation-rules#percentage-rollouts), if I evaluate with a context/multi-context that does contain my rollout context kind, what would happen for 1) the segment result 2) a flag's custom rule result?

**Comment by ozheng-circle** [comment]
And, `rules.clauses.context_kind` doesn't have anything to do with `weight` since it's specific to the rule? I believe the documentation is incorrect on that.

**Comment by sloloris** [comment]
Hi @ozheng-circle ! Happy to help :)

> And, rules.clauses.context_kind doesn't have anything to do with weight since it's specific to the rule? I believe the documentation is incorrect on that.

This is correct! I have removed that sentence entirely and will roll the updated documentation into a release later this week.

> Another thing is in the segment UI, there doesn't appear to be an option to bucket by a rollout context's attribute.

This option will only appear for rule-based segments. Unfortunately, you have to choose the type of segment (rule-based or list-based) upon segment creation. If you are working with a list-based segment, the option will not appear.

> For [percentage rollout](https://docs.launchdarkly.com/sdk/concepts/flag-evaluation-rules#percentage-rollouts), if I evaluate with a context/multi-context that does contain my rollout context kind, what would happen for 1) the segment result 2) a flag's custom rule result?

I'm not 100% sure I've understood your question correctly, but I am guessing that in (1) you are asking how the segment with a rollout context kind set will evaluate a multi-context. In this case, I am fairly certain that it would probabilistically (depending on how far along in your rollout you are) include or exclude that multi-context, if that makes sense. We then save the configuration. For example, say you're 60% rolled out on `organization` kind, and you have a multi-context that includes an `organization` and `user` context. At this point, you should be rolled out to 60% of organizations, so you'd probably have a 60% chance of that multi-context being included in the segment. The `user` context is irrelevant here even though it is included in the multi-context - unless there is a prior segment rule that applies.

For (2), if you mean how a flag would evaluate with similar rules to the above, it would be pretty much the same. If you are evaluating on a segment, it would depend entirely on whether or not the context had made it into that segment. However, it's important to always keep in mind that flag and segment rules evaluate in order - a context will be evaluated by each rule in order and only if none of the rules apply to it will the default be applied. If an earlier rule puts it in a non-default variation, later rules will not apply.

This is not my area so I will follow up with someone who works on this specifically to make sure I haven't given you any false information. If this was not your question, or if you have any further questions, please reach out to our support team! They're much more well-acquainted with broad areas of the product and can probably give you more confident answers.

Have a great week!
