### ISSUE TITLE
Submit GPG key to the OpenTofu registry

### ISSUE THREAD

**Issue by tthompson-figma** [launchdarkly/terraform-provider-launchdarkly#221]
We would like to migrate to OpenTofu with all providers' GPG signatures validated. However, OpenTofu skips validation for this provider because the OpenTofu registry does not have this provider's GPG key.

You can follow this link to submit it: [Submit new Provider Signing Key](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+)

If you don't have access to the public key anymore, you can retrieve it from the Terraform registry:

```bash
curl 'https://registry.terraform.io/v1/providers/launchdarkly/launchdarkly/2.9.2/download/linux/amd64' | jq --raw-output '.signing_keys | .gpg_public_keys | .[0] | .ascii_armor'
```

**Note:** For security reasons, it has to be submitted by the provider author for the OpenTofu registry to accept it.

**Alternatives considered**
Out-of-band GPG validation for providers missing keys in the OpenTofu registry. This is a pain :)

**Additional context**
OpenTofu is a fork of Terraform that is open-source, community-driven, and managed by the Linux Foundation.
Hashicorp https://github.com/opentofu/roadmap/issues/24#issuecomment-1699535216 for the terraform provider registry to disallow usage with things other than terraform, so OpenTofu had to build its own registry.

**Potential impact**
Allows OpenTofu users to use this provider with the same security guarantees they would using Terraform.

**Comment by sloloris** [comment]
Hi @tthompson-figma ! Thanks for bringing this to our attention and for providing such thorough instructions!

I've submitted our public key via the link you provided; [here](https://github.com/opentofu/registry/issues/1215) is the issue. I will follow up here if there is any movement.

I hope we're able to unblock you quickly!

**Comment by jrioux-trustii** [comment]
Hi, we have this issue in our pipeline following this change
![image](https://github.com/user-attachments/assets/eae74970-976b-4b70-924e-cedd893bd0f0)

Is there a wait time for the key to propagate? Or do we need to clear something on our side?

**Comment by nicolaschambrier** [comment]
> Hi, we have this issue in our pipeline following this change ![image](https://private-user-images.githubusercontent.com/186610027/380793429-eae74970-976b-4b70-924e-cedd893bd0f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTAyODksIm5iZiI6MTczMDE4OTk4OSwicGF0aCI6Ii8xODY2MTAwMjcvMzgwNzkzNDI5LWVhZTc0OTcwLTk3NmItNGI3MC05MjRlLWNlZGQ4OTNiZDBmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwODE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2JkMTI3MGI0YjVkNzIxODE1YTRlZTY0OTY3ZWZmMGFlMDU2YTcwNGUxYzFjN2I1YzYwOGYwMjUxM2U0ZmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gkfzRn5RRSBNQpOBD9IdSU7T-XYVCTFPbQ8gz273tD8)
> 
> Is there a wait time for the key to propagate? Or do we need to clear something on our side?

Same issue here

**Comment by sloloris** [comment]
@tthompson-figma the [original addition](https://github.com/opentofu/registry/issues/1215) of the GPG key [was reverted](https://github.com/opentofu/registry/pull/1224) because of the discussion above. Since it seems we can have more than one key for different versions of the LD provider, I want to just quickly check in as to whether you do in fact need the key associated with v2.9.2 of our provider, in which case I will try to revert the revert. In the meantime, I have [submitted the more recent one.](https://github.com/opentofu/registry/pull/1229)

**Comment by tthompson-figma** [comment]
@sloloris thanks for checking in! I think we're fine to upgrade our minor version instead of you all needing to keep the old key around :)

**Comment by sloloris** [comment]
Wonderful! In that case @mguillet-payfit, @nicolaschambrier, @jrioux-trustii the new key [has merged](https://github.com/opentofu/registry/pull/1229). Please let us know if you continue to have issues but I will close this issue for now!
