### ISSUE TITLE
launchdarkly_environment_feature_flags not always destroyed

### ISSUE THREAD

**Issue by wondersd** [launchdarkly/terraform-provider-launchdarkly#30]
We've been using the terraform launchdarkly provider (v1.3.2) to manage test launch darkly environments for CI builds. This consists of creating an `launchdarkly_environment` resource and filling it in with `launchdarkly_feature_flag_environment` and `launchdarkly_segment` resources populated with desired rules.

For the most part this works fine and we're able to have many builds operating on their own namespace separated environments.

However, it's become apparent that the destruction of these environments via `terraform destroy` does not always complete successfully.

```
09:00:56  Error: failed to update flag "feature-x" in project "default", environment "PR-x": 400 Bad Request: {"code":"invalid_request","message":"unknown segment \"foo\""}
```

The segment referenced is one in the `rules` block of the environment feature flag with a `segmentMatch` clause. Inspecting that env after the failed destruction shows that the segment 'foo' does in fact exist and the audit log of that environment shows no entries for attempting to delete that segment. `terraform graph` also shows expected dependencies between the segment and environment feature flag (environment flag -> segment).

**Comment by ldhenry** [comment]
Hey @wondersd,

I'm glad you are getting good use out of the provider. Do you happen to know if the behavior is consistent for all feature_flag_environments with segment rules or is it somewhat random? 

In any case, I've filed an internal ticket to address this bug, and I'll be sure to update this issue with further questions and/or to notify you of a fix.

Thanks,
Henry

**Comment by wondersd** [comment]
@ldhenry 

First, thanks for the quick response!

It seems to happen with any `feature_flag_environment`, though usually only one or two any given time it fails (the exact one or two appears to be random and sometimes it just works)

All of our `feature_flag_environment` have at least one `segmentMatch` rule, some have two. That doesn't seem to effect which are susceptible. Don't know if this issue effects `feature_flag_environment` resources that don't have any rules or different rule clauses.

I would venture a guess based of the error message that its a problem with the `segmentMatch` clause in particular.

Thanks,

Don

**Comment by ldhenry** [comment]
Thanks, that's helpful information. It sounds like a race condition that we'll have to spend some time investigating. In the meantime you might be able to get around it by reducing Terraform’s parallelism parameter, though your double destroy approach may be more efficient. 

I'll be sure to update this issue as soon as a fix is in place.

Thanks,
Henry

**Comment by wondersd** [comment]
@ldhenry still running into this. 

I think the provider here can avoid this by first checking that the environment exists before attempting to read either `launchdarkly_feature_flag_environment ` or `launchdarkly_segment` resources. If the environment no longer exists then both of those reads can safely return nothing and treat the resource as non existant.

**Comment by ldhenry** [comment]
@wondersd, I'm going to close this one for now since you mentioned you haven't seen it recently. Feel free to re-open this issue if it comes up again.

Our team will be investigating and hopefully fixing #101  next week, so stayed on that one.
