### ISSUE TITLE
Feature Request: update flag status via TF

### ISSUE THREAD

**Issue by hsy3418** [launchdarkly/terraform-provider-launchdarkly#40]
Our team would love to control the flag on/off status via TF, as we are managing a big team and there will be multiple projects and feature flags be used. It would be cool to manage the feature flags in the gitops style, and we want a PR to change a toggle state.

**Comment by ldhenry** [comment]
Hello @hsy3418,

I appreciate your interest in the LaunchDarkly Terraform provider. As I understand your request, you should be able to use the [`launchdarkly_feature_flag_environment`](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/feature_flag_environment) resource to manage flag targeting today. You can use the `targeting_enabled` argument to set the flag ON/OFF. Additionally, you can use that resource to set custom targeting rules, percentage roll outs,  and individual user targets. 

We have a few examples [here](https://github.com/launchdarkly/terraform-provider-launchdarkly/tree/master/examples/feature_flags) that might be of interest to you.

I'm going to close this issue for now, but feel free to re-open it if I misunderstood your request or if that resource doesn't cover exactly what you need.

Thanks,
Henry
