### ISSUE TITLE
Support for flag triggers

### ISSUE THREAD

**Issue by keirlawson** [launchdarkly/terraform-provider-launchdarkly#44]
It would be great to be able to use terraform to set up flag triggers (https://launchdarkly.com/blog/launched-automatic-kill-switches-using-flag-triggers/), presently this only seems to be possible using the UI?

**Comment by ldhenry** [comment]
Hi @keirlawson,

We're happy to see that you are interested in managing flag triggers via Terraform. I agree that this feature would be a natural fit for the LaunchDarkly Terraform provider and I have filed an internal ticket to get this work scheduled.

I'll be sure to update this issue when the the feature is released.

Cheers,
Henry

**Comment by sloloris** [comment]
Hi @keirlawson I'm so sorry this has been such a long time coming, but we've just published v2.4.0 of the provider with new support for flag triggers. If you do get to using it, please feel free to reach out with any feedback you have!

**Comment by jeffWelling** [comment]
Just to clarify a minor piece of example from the docs, the example shown shows the following:

```
    instructions {
        kind = "turnFlagOn"
    }
```

Was this perhaps meant to be 

```
    instructions = {
        kind = "turnFlagOn"
    }
```

**Comment by jeffWelling** [comment]
In the interest of saving time for anyone who's trying trying out this awesome new support for flag triggers, I think I may have found a bug where I cannot seem to create an enabled trigger, I've raised an issue about it here: https://github.com/launchdarkly/terraform-provider-launchdarkly/issues/81

I'm sure it'll be fixed promptly just FYI if you see stacktraces as well
