### ISSUE TITLE
Terraform 0.14.6 - Failed to query available provider packages

### ISSUE THREAD

**Issue by masonhuemmer** [launchdarkly/terraform-provider-launchdarkly#48]
Below is my configuration

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/49791141/107600041-24dd4e00-6be8-11eb-8c47-3a47500ca43c.png">

Receiving the following error. 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/49791141/107600019-0e36f700-6be8-11eb-8d7d-e91e8292c4db.png">

<img width="652" alt="image" src="https://user-images.githubusercontent.com/49791141/107600329-0b88d180-6be9-11eb-8133-87014140f376.png">

**Comment by masonhuemmer** [comment]
I was able to resolve it by adding the following to the module.

<img width="652" alt="image" src="https://user-images.githubusercontent.com/49791141/107600624-ed6fa100-6be9-11eb-9e44-4ec72e6e2d7e.png">

**Comment by ldhenry** [comment]
Hi @masonhuemmer,

Thanks for bringing this to our attention. I've created an internal ticket to track this issue and I'll be sure to update you here when we have a suitable fix.

Thanks,
Henry

**Comment by sloloris** [comment]
Hi @masonhuemmer, 

Before proceeding, is it possible you've uploaded the wrong screenshot in your follow-up comment? It appears to be exactly the same as the first one. Is it that the former is your Terraform config and the latter from your module config?

Regarding your comment about best practices in module declaration, I'm not quite sure what you mean - per the [official Terraform docs](https://www.terraform.io/docs/language/modules/develop/providers.html#provider-version-constraints-in-modules), the solution you found is the recommended approach. 

Please let me know if you can provide any further information so I can investigate further. Thanks!

**Comment by masonhuemmer** [comment]
So the screenshot is actually different. I had to place the provider resource at the module level.

Best practice, Terraform recommends configuring all providers at the root level. If you look at the original error, it recommends that you add the provider to each module it is calling.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sloloris** [comment]
Hi @masonhuemmer, 

Although unfortunate, I'm not sure at this point if there's anything we can do about it as the practice of declaring providers without modules is something specified by Terraform, not the providers. From my understanding, it is acceptable to do so. Here's [what Hashicorp has to say](https://www.terraform.io/docs/language/modules/develop/providers.html#provider-version-constraints-in-modules): 

> Although provider configurations are shared between modules, each module must declare its own provider requirements, so that Terraform can ensure that there is a single version of the provider that is compatible with all modules in the configuration and to specify the source address that serves as the global (module-agnostic) identifier for a provider.

I hope this helps!

**Comment by masonhuemmer** [comment]
I just can’t use your provider since we heavily use modules. If we need to remove or take down resources, it will become an issue.

I still don’t exactly understand why this is not an issue with Azure or AWS or Kubernetes providers.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
