### ISSUE TITLE
undesired default environment created with launchdarkly_project

### ISSUE THREAD

**Issue by gneveu** [launchdarkly/terraform-provider-launchdarkly#58]
Hello,

We noticed that if we declare our environments (DEV,PRE,PROD) in `launchdarkly_environment` blocks outside of `launchdarkly_project`, then a default 'Test' and 'Production' environments get created. Which may conflict with our own definition of declared environments (as they could have the same key)

```
resource "launchdarkly_project" "myproject" {
 ...
}

resource "launchdarkly_environment" "dev" {
...
project_key = launchdarkly_project.myproject.key
}

resource "launchdarkly_environment" "pre" {
...
project_key = launchdarkly_project.myproject.key
}

resource "launchdarkly_environment" "prod" {
...
project_key = launchdarkly_project.myproject.key
}
```

For some reason the problem doesn't appear if declare DEV/PRE/PROD as nested blocks inside the `launchdarkly_project`:

```
resource "launchdarkly_project" "myproject" {
 ...
environments {
...
}

environments {
...
}

environments {
...
}
}
```

the nested blocks seems to be a deprecated attribute so we would like to use `launchdarkly_environment` resources ideally

provider version: 1.5.1
terraform version: 0.13.6

**Comment by gneveu** [comment]
ok, just noticed this in the doc: https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/project#environments

**Comment by ldhenry** [comment]
Hi @gneveu,

Starting in v1.2.1, the environments block was deprecated, however we found a suitable way to to support the nested environments block in v1.5.0, so we removed the deprecation warning from the provider and plan to maintain support going forward.

With that being said, there may be some residual warning messages we need to clean up. Are you still seeing  the deprecation warning when you a plan/apply on v1.5.1?

Thanks,
Henry

**Comment by gneveu** [comment]
Hello @ldhenry,

Indeed I am still seeing the deprecation warning for nested environment blocks in IntelliJ although I don't see it when running the plan/apply with 1.5.1 version of the provider. This is what confused me in the first place.
I guess the "issue" is more on the terraform plugin for IntelliJ.

**Comment by ldhenry** [comment]
Yeah, sorry for the confusion on this. It sounds like the IntelliJ Terraform plugin is still using an outdated version of the provider. I would expect it to be able to detect the required version from the `required_providers` block in your config but I'm not really sure to be honest.

I'm going to close this ticket for now, but feel free to reopen it if you run into anymore unexpected behavior around this.
