### ISSUE TITLE
Provider fails to create flags with empty string variation

### ISSUE THREAD

**Issue by swisspol** [launchdarkly/terraform-provider-launchdarkly#60]
Observed with 1.6.0

If you have a flag of type `string` with a variation like this (an empty string, which is allowed in LaunchDarkly UI):
```
...
  variations {
    value = ""
  }
...
```

It will create a plan like:
```
...
+ variations {}
...
```

Applying Terraform to create the new flag will fail with this obscure error:
```
launchdarkly_feature_flag.mhc-infrastructureintegration-esmetricsurl: Creating...

Error: rpc error: code = Unavailable desc = transport is closing
```

**Comment by sloloris** [comment]
Hi @swisspol, 

We are looking into this for you now and will hopefully get back to you with an answer in the next week. I apologize for any issues this may be causing you.

**Comment by sloloris** [comment]
Hi @swisspol,

While we work on getting a fix rolled out, it looks like it will work if you pass any other optional properties on the variation in, i.e.
```
variations {
  value = ""
  name = "empty string"
}
```
I hope this is an acceptable workaround while we work on the release. Please let me know if you have any trouble.

**Comment by swisspol** [comment]
Thanks much for following up!
