### ISSUE TITLE
launchdarkly_feature_flag_environment apply does not remove user targets

### ISSUE THREAD

**Issue by hsy3418** [launchdarkly/terraform-provider-launchdarkly#62]
Hi,

I think this might be relevant to issue #45, so basically when try to remove a user_targets block from launchdarkly_feature_flag_environment, I would expect the user target will be removed and picked by the pipeline, but terraform plan shows no changes.

**Comment by ldhenry** [comment]
Hi @hsy3418,

Thanks for reporting this. We are actively working on fixing this in our upcoming v2 release. I'll be sure to update this issue when the release is live.

Thanks,
Henry

**Comment by sloloris** [comment]
Hi @hsy3418,

This has also been resolved as part of the v2.0.0 release of our provider. Please let us know if you have any questions or issues moving forward and thank you for actively helping us to improve our provider!
