### ISSUE TITLE
Feature Request- Add ability for specify archiving an feature flag using launchdarkly_feature_flag

### ISSUE THREAD

**Issue by hsy3418** [launchdarkly/terraform-provider-launchdarkly#63]
Hi,
We are using terraform to manage the full life cycle of feature flags in terraform from creation to deletion. The current issue with deletion of feature flag is as long as we remove an existing feature flag from terraform, it will be deleted without any checking if the feature flag is safe to be deleted, while the LaunchDarkly itself has the archiving ability to check if the flag has any dependencies that will not let users to delete it. So that feature will be nice to have in terraform  by providing an `archive` attribute to launchdarkly_feature_flag, by default it is of course false, and when users trying to archive a flag, and it will set archive = true and the LD api can check if the flag is safe to be archived and return error message if the flag has dependency.

**Comment by ldhenry** [comment]
Hey @hsy3418,

This is a great suggestion and should be fairly straightforward to add. I've created an internal ticket to track this and will update this issue when the provider is updated to include this feature.

Thanks,
Henry

**Comment by sloloris** [comment]
Hi @hsy3418,

Just some casual housekeeping - we did actually add this feature with release 2.1.0 but I forgot to close this issue. I hope that you will be able to make good use of it if you haven't already!
