### ISSUE TITLE
Terraform-managed feature flag with external intergration

### ISSUE THREAD

**Issue by alarrosa14** [launchdarkly/terraform-provider-launchdarkly#69]
We're currently handling feature flag creation using Terraform. At the same time, we have an external integration with Jira which sets `custom_properties` to the feature flag.
That `custom_properties` are not set in the Terraform code and, as they seem to default to `null`, `custom_properties` are planned to be destroyed in any subsequent `terraform plan` execution.
Is this an expected behavior? If that's the case it will make integrations difficult to use if the FF are managed with Terraform.

**Comment by ldhenry** [comment]
Hey @alarrosa14,

Thanks for bringing this to our attention. In general Terraform wants your config file to be the source of truth for all of the resource's attributes. However, you can use the the [`ignore_changes` argument of the `lifecycle` meta-argument](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes) to signal that some of the resource is managed elsewhere. For your use case, you should be able to do something like this:
``` hcl
resource "launchdarkly_feature_flag" "building_materials" {
  lifecycle {
    ignore_changes = [custom_properties]
  }

  project_key        = "henrys-v2-project"
  key                = "building-materials"
  name               = "Building materials"

  variation_type = "string"
  variations {
    value       = "sticks"
  }
  variations {
    value       = "straw"
  }
}
```

This should let you use our Jira integration to manage the flag's custom properties and Terraform for everything else. Please let me know if you run into any trouble with this approach.

Thanks,
Henry

**Comment by ldhenry** [comment]
No problem at all. I'm going to close this issue for now, but feel free to re-open if it's not behaving as you would expect.
