### ISSUE TITLE
Rules within "launchdarkly_segment" are not applied by default 

### ISSUE THREAD

**Issue by stephledev** [launchdarkly/terraform-provider-launchdarkly#79]
When creating a segment with the `launchdarkly_segment` resource any defined `rules` within will show an extra "then-clause" in the LaunchDarkly app interface:

<img src="https://user-images.githubusercontent.com/6168494/150346606-3afb16c3-be71-4339-9598-a4309cf14391.png" width="400">

This option by default is set to include 0% of all users targeted which effectively makes it deactivated. The [rules block](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/segment#rules) within the `launchdarkly_segment` has no option to override this. When creating a new rule through the app interface, this "then-clause" doesn't pop up.

Is this intentional? Is there a possibility to add support to control this?

**Comment by stephledev** [comment]
thanks for your response @ldhenry. tested your workaround and it works 👌 let me know when there is a fix available.

**Comment by ldhenry** [comment]
Hey @stephledev, we just released a fix for this issue in [v2.4.1](https://github.com/launchdarkly/terraform-provider-launchdarkly/releases/tag/v2.4.1). Thanks for bringing this to our attention.
