### ISSUE TITLE
Support for Teams Resource + Data Source

### ISSUE THREAD

**Issue by ashwinv11** [launchdarkly/terraform-provider-launchdarkly#86]
Hey there,

Really excited about the new [Teams](https://docs.launchdarkly.com/home/teams) feature! Could we get resources + data sources for this feature in the LaunchDarkly Provider?

This would allow us to automate user permission management a lot easier!

**Comment by ldhenry** [comment]
Hey @ashwinv11,

I'm glad to hear your excited about the Teams feature. We plan to begin work on this as soon as the application team takes the [API endpoints](https://apidocs.launchdarkly.com/tag/Teams-(beta)) out of beta. I'll submit an internal feature request to register your interest and excitement. I'll be sure to update this issue with any updates on our progress.

Thanks,
Henry

**Comment by davidswyftx** [comment]
@ldhenry Teams looks to be out of Beta now 🥳 Any chance we can bump this one?

**Comment by LavaToaster** [comment]
Hey, @ldhenry I've been advised that this was put into the sprint last week, do you know if this is close to being worked on and done?

**Comment by ldhenry** [comment]
Hey @davidswyftx and @LavaToaster. The team is working on it as we speak. We'll be sure to update this issue once the release is out in the wild.

**Comment by emkoehler** [comment]
Hi @ashwinv11! I just wanted to let you know that today we released the [team resource as part of our Terraform provider](https://registry.terraform.io/providers/launchdarkly/launchdarkly/latest/docs/resources/team) that you previously requested. Excited to hear how it works out for you!

Sincerely,
Emily

**Comment by ashwinv11** [comment]
Woohoo! Thank you @emkoehler!
