### ISSUE TITLE
Support New Terraform Block Syntax

### ISSUE THREAD

**Issue by bschaeffer** [launchdarkly/terraform-provider-launchdarkly#93]
For a while, the terraform SDK has supported [named block syntax](https://github.com/hashicorp/terraform-plugin-sdk/issues/220), enabling moving from index based (which is hard to track changes too)

```
variations {
  name  = "foo"
  value = "foo"
}
variations { 
  name  = "bar"
  value = "bar"
}
```

To map based, named blocks:

```
variations "foo" {
  value = "foo"
}
variations "bar" { 
  value = "bar"
}
```

Are there any plans to migrate to this new syntax? 

I think it might make issues like #92 way harder to hit, but it would surely prevent confusing plans in an index based scenario. A index based plan where `0 = foo, 1 = bar` and we want to remove `foo` goes from this where it looks like we are deleting bar and renaming foo (not sure if that is what is happening under the hood):

```
  ~ variations {
    ~ value       = "foo" -> "bar"
  }
  - variations {
    - value       = "bar"
  }
```

to this in a map-based, named block world where it looks like we are removing foo:

```
- variations "foo" {
  - value       = "foo"
  }
  variations {
    value       = "bar"
  }
```

**Comment by sloloris** [comment]
Hi @bschaeffer!

We do not currently plan to implement this in the near future, but we will keep an eye on how the SDKs continue to develop and inform you if that ever changes. But thank you for bringing this to our attention! It's a great thing to have on our radar.
