### ISSUE TITLE
`basePermissions` is not supported in `launchdarkly_custom_role`

### ISSUE THREAD

**Issue by stevengonsalvez** [launchdarkly/terraform-provider-launchdarkly#95]
There is no base permission parameter (as per UI or API) in the launch darkly provider for the custom role

**Comment by ldhenry** [comment]
Hey @stevengonsalvez,

Thanks for bringing this to our attention. I've created an internal ticket to track this work. We'll try to get it out in the next release.

Thanks,
Henry
